-- ============================================================================
-- 128_receipts_server_side regression test — Supabase SQL editor.
-- ============================================================================
-- Run AFTER supabase/migrations/128_receipts_server_side.sql.
-- Exercises FINANCE HARDENING ITEM 5:
--   A. RPC-recorded payment   → exactly one receipts row with its receipt_no;
--   B. legacy DIRECT insert   → receipt row auto-created from payment data;
--   C. legacy null receipt_no → receipt row generated by next_receipt_number.
-- Transaction ROLLBACKs at the end; synthetic year 9999.
-- ============================================================================

BEGIN;

DO $$
DECLARE
  v_school  UUID; v_student UUID; v_profile UUID;
  v_pay_id  UUID;
  v_res     JSONB;
  v_cnt     INT;
  v_total   NUMERIC;
  v_receipt TEXT;
BEGIN
  SELECT s.id INTO v_school
  FROM schools s JOIN students st ON st.school_id = s.id
  ORDER BY s.created_at DESC LIMIT 1;
  IF v_school IS NULL THEN RAISE EXCEPTION 'FAILED setup: no school with students'; END IF;
  SELECT id INTO v_student FROM students WHERE school_id = v_school LIMIT 1;
  SELECT id INTO v_profile FROM profiles WHERE school_id = v_school LIMIT 1;

  -- ── A. RPC path ───────────────────────────────────────────────────────────
  v_res := record_fee_payment(
    v_school, v_student, 1200, 'cash', 'cash', NULL, 'MP-300', 'TEST-RCT-128-A',
    v_profile, CURRENT_DATE, 'Term 1', 9999, 'AUTOTEST A');
  IF (v_res->>'success')::boolean IS NOT TRUE THEN RAISE EXCEPTION 'FAILED A: %', v_res->>'error'; END IF;
  v_pay_id := (v_res->>'payment_id')::uuid;

  SELECT count(*) INTO v_cnt FROM receipts WHERE payment_id = v_pay_id;
  IF v_cnt <> 1 THEN RAISE EXCEPTION 'FAILED A: % receipts rows (expected exactly 1)', v_cnt; END IF;
  SELECT receipt_number, total_amount INTO v_receipt, v_total FROM receipts WHERE payment_id = v_pay_id;
  IF v_receipt <> 'TEST-RCT-128-A' THEN RAISE EXCEPTION 'FAILED A: receipt_no=%', v_receipt; END IF;
  IF v_total <> 1200 THEN RAISE EXCEPTION 'FAILED A: total_amount=%', v_total; END IF;
  RAISE NOTICE 'PASS A: RPC payment → deterministic receipt row';

  -- ── B. legacy direct insert (bypasses the RPC entirely) ──────────────────
  INSERT INTO fee_payments
    (school_id, student_id, amount, payment_type, payment_method,
     receipt_number, received_by, transaction_date, term, year)
  VALUES
    (v_school, v_student, 850, 'cash', 'cash',
     'TEST-RCT-128-B', v_profile, CURRENT_DATE, 'Term 3', 9998)
  RETURNING id INTO v_pay_id;

  SELECT count(*) INTO v_cnt FROM receipts WHERE payment_id = v_pay_id;
  IF v_cnt <> 1 THEN RAISE EXCEPTION 'FAILED B: % receipts rows (expected 1)', v_cnt; END IF;
  SELECT receipt_number, term, year INTO v_receipt, v_total, v_cnt FROM receipts WHERE payment_id = v_pay_id;
  IF v_receipt <> 'TEST-RCT-128-B' THEN RAISE EXCEPTION 'FAILED B: receipt_no=%', v_receipt; END IF;
  RAISE NOTICE 'PASS B: direct insert → receipt row created';

  -- ── C. legacy insert with NO receipt number → server-generated ───────────
  INSERT INTO fee_payments
    (school_id, student_id, amount, payment_type, payment_method,
     received_by, transaction_date, term, year)
  VALUES
    (v_school, v_student, 410, 'bank', 'bank',
     v_profile, CURRENT_DATE, 'Term 1', 9997)
  RETURNING id INTO v_pay_id;

  SELECT count(*) INTO v_cnt FROM receipts WHERE payment_id = v_pay_id;
  IF v_cnt <> 1 THEN RAISE EXCEPTION 'FAILED C: % receipts rows (expected 1)', v_cnt; END IF;
  SELECT receipt_number INTO v_receipt FROM receipts WHERE payment_id = v_pay_id;
  IF v_receipt IS NULL OR v_receipt = '' THEN RAISE EXCEPTION 'FAILED C: receipt_no not generated'; END IF;
  RAISE NOTICE 'PASS C: null receipt_no → generated %', v_receipt;

  -- ── done ─────────────────────────────────────────────────────────────────
  RAISE NOTICE 'ALL 128 TESTS PASSED — transaction ROLLBACK, nothing persisted.';
END;
$$;

ROLLBACK;