import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { PAGE, fmtDate } from './schoolPdfTemplate'
import { memberTypeLabel } from '../lib/library'

const M = PAGE.MARGIN
const W = PAGE.W
const CX = PAGE.CENTER
const CW = PAGE.CONTENT_W

const BLACK = [10, 10, 10]
const DARK = [45, 45, 45]
const GRAY = [110, 110, 110]
const LIGHT = [220, 220, 220]
const ROW_BG = [248, 248, 248]
const HEAD_BG = [232, 232, 232]

function fmtShort(d) {
  if (!d) return '—'
  return new Date(d).toLocaleDateString('en-KE', { day: '2-digit', month: 'short', year: 'numeric' })
}

function memberIdentifier(student, teacher, member) {
  if (student) return student.admission_number || student.kemis_number || student.nemis_number || ''
  if (teacher) return teacher.staff_number || teacher.teacher_code || teacher.employee_number || ''
  return member?.member_code || ''
}

export function exportMemberRecordPdf({ school, member, student, teacher, loans }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  let y = M

  // ── School header (grayscale) ──
  if (school?.name) {
    doc.setFont('times', 'bold')
    doc.setFontSize(16)
    doc.setTextColor(...BLACK)
    doc.text(String(school.name).toUpperCase(), CX, y, { align: 'center' })
    y += 7

    if (school.motto) {
      doc.setFont('times', 'italic')
      doc.setFontSize(9)
      doc.setTextColor(...GRAY)
      doc.text(`"${school.motto}"`, CX, y, { align: 'center' })
      y += 5
    }

    const contact = [school.address, school.phone, school.email].filter(Boolean)
    if (contact.length) {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(...GRAY)
      doc.text(contact.join('  |  '), CX, y, { align: 'center', maxWidth: CW })
      y += 5
    }
    y += 2
    doc.setDrawColor(...DARK)
    doc.setLineWidth(0.5)
    doc.line(M, y, W - M, y)
    y += 6
  }

  // ── Title ──
  doc.setFont('times', 'bold')
  doc.setFontSize(13)
  doc.setTextColor(...BLACK)
  doc.text('LIBRARY MEMBER RECORD', CX, y, { align: 'center' })
  y += 7

  // ── Member info ──
  const regNo = memberIdentifier(student, teacher, member)
  const info = [['Member Name', member.full_name]]
  if (regNo) info.push(['Reg / Adm No', regNo])
  info.push(['Role', memberTypeLabel(member.member_type)])
  info.push(['Member ID', member.member_code || '—'])
  if (member.email) info.push(['Email', member.email])
  info.push(['Member Since', fmtDate(member.created_at)])
  info.push(['Status', member.status])

  autoTable(doc, {
    startY: y,
    body: info.map(([k, v]) => [k, v]),
    styles: { fontSize: 9, cellPadding: 2.5, font: 'times', textColor: DARK, lineColor: LIGHT, lineWidth: 0.15 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50, fillColor: HEAD_BG } },
    margin: { left: M, right: M },
    theme: 'grid',
  })
  y = doc.lastAutoTable.finalY + 6

  // ── Loans table ──
  doc.setFont('times', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(...BLACK)
  doc.text('BOOK LOANS', M, y)
  y += 5

  const rows = (loans || [])
    .slice()
    .sort((a, b) => new Date(a.issued_at || a.created_at) - new Date(b.issued_at || b.created_at))

  const body = rows.map((l, i) => [
    String(i + 1),
    l.books?.title || '—',
    l.copy?.copy_code || '—',
    fmtShort(l.issued_at || l.created_at),
    l.returned_at ? fmtShort(l.returned_at) : '—',
    l.status === 'lost' ? 'Yes' : '—',
    l.status === 'damaged' ? 'Yes' : '—',
  ])

  autoTable(doc, {
    startY: y,
    head: [['No.', 'Book Name / Title', 'Book Code', 'Date Issued', 'Date Returned', 'Lost', 'Damaged']],
    body,
    styles: { fontSize: 8, cellPadding: 2.5, font: 'times', textColor: DARK, lineColor: LIGHT, lineWidth: 0.15 },
    headStyles: { fillColor: HEAD_BG, textColor: BLACK, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: ROW_BG },
    columnStyles: {
      0: { cellWidth: 12, halign: 'center' },
      1: { cellWidth: 60 },
      2: { cellWidth: 25 },
      3: { cellWidth: 26 },
      4: { cellWidth: 26 },
      5: { cellWidth: 12, halign: 'center' },
      6: { cellWidth: 13, halign: 'center' },
    },
    margin: { left: M, right: M },
    theme: 'grid',
  })

  y = doc.lastAutoTable.finalY + 5
  doc.setFont('times', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...GRAY)
  doc.text(`Total loans: ${rows.length}  ·  Generated by ShulePulse ERP — ${fmtDate(new Date())}`, M, y)

  const safeName = (member.full_name || 'member').replace(/\s+/g, '_')
  doc.save(`${safeName}_library_record.pdf`)
}
