/**
 * Teacher Weekly Timetable PDF renderer (A4 landscape).
 * Mirrors the on-screen print-area layout so the downloaded file matches
 * what the teacher sees. Works in web browsers AND the Capacitor APK
 * (blob + anchor download pattern shared across the app).
 */
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { drawSchoolHeader, FONT } from './schoolPdfTemplate'

const F = FONT.SANS

export async function buildTimetablePdfBlob({
  school,
  profile,
  teacherCode = '',
  timetable,
  slots = [],
  getCell,
  days = [],
  dayShort = {},
}) {
  const doc = new jsPDF('landscape', 'mm', 'a4')
  const W = 297
  const M = 12
  const CX = 148.5
  const totalDays = days.length || 5

  // ── Branded school header ────────────────────────────────
  let y = 10
  try {
    y = await drawSchoolHeader(doc, school, {
      y: 8,
      orientation: 'landscape',
      showMotto: false,
      showContact: false,
    })
  } catch {
    y = M + 8
  }

  // ── Title block ──────────────────────────────────────────
  y += 3
  doc.setFont(F, 'bold')
  doc.setFontSize(14)
  doc.setTextColor(30, 58, 95)
  doc.text('WEEKLY TIMETABLE', CX, y, { align: 'center' })
  y += 5.5

  doc.setFont(F, 'normal')
  doc.setFontSize(9)
  doc.setTextColor(40, 40, 40)
  const teacherLabel = `${profile?.full_name || 'Teacher'}${teacherCode ? ` (${teacherCode})` : ''}`
  doc.text(teacherLabel, CX, y, { align: 'center' })
  y += 4.5

  doc.setFontSize(8)
  doc.setTextColor(110, 110, 110)
  doc.text(
    `${days[0] || 'Monday'} – ${days[days.length - 1] || 'Friday'}  |  Generated ${new Date().toLocaleDateString('en-KE')}`,
    CX,
    y,
    { align: 'center' }
  )
  y += 4

  // ── Build grid ───────────────────────────────────────────
  const head = [['DAY', ...slots.map(s => (s.type === 'break' ? s.breakLabel : s.label))]]

  const body = days.map((day, di) => {
    const row = []
    slots.forEach(slot => {
      if (slot.type === 'break') {
        if (di === 0) {
          row.push({
            content: slot.breakLabel,
            colSpan: totalDays,
            styles: {
              fillColor: [243, 244, 246],
              textColor: [120, 120, 120],
              fontStyle: 'italic',
              fontSize: 6.5,
              halign: 'center',
              valign: 'middle',
            },
          })
        }
        return
      }

      const cell = getCell(day, slot.period)
      if (cell) {
        const subj = cell.subject_code || (cell.subject_name || '').slice(0, 4).toUpperCase()
        const cls = `${(cell.class_name || '').trim()}${cell.class_stream ? ` ${cell.class_stream}` : ''}`
        row.push({
          content: [[subj], [cls]],
          styles: { fontSize: 7.5, halign: 'center', valign: 'middle', lineColor: [40, 40, 40], lineWidth: 0.12 },
        })
      } else {
        row.push({
          content: '\u2013',
          styles: { fontSize: 8, textColor: [190, 190, 190], halign: 'center', valign: 'middle' },
        })
      }
    })
    return [
      {
        content: dayShort[day] || day.slice(0, 3).toUpperCase(),
        styles: { fontStyle: 'bold', fillColor: [245, 245, 245], halign: 'center', valign: 'middle' },
      },
      ...row,
    ]
  })

  autoTable(doc, {
    startY: y,
    head,
    body,
    theme: 'grid',
    tableLineColor: [40, 40, 40],
    tableLineWidth: 0.2,
    styles: { fontSize: 7.5, cellPadding: 1.6, font: F, valign: 'middle', tableLineWidth: 0.15 },
    headStyles: {
      fillColor: [30, 58, 95],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 7,
      halign: 'center',
      valign: 'middle',
    },
    columnStyles: { 0: { cellWidth: 15, halign: 'center', fontStyle: 'bold' } },
    margin: { left: M, right: M },
  })

  const fy = Math.max(doc.lastAutoTable.finalY, 160) + 10
  doc.setFont(F, 'normal')
  doc.setFontSize(8.5)
  doc.setTextColor(40, 40, 40)
  doc.text('PREPARED BY: \u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026', M, fy)
  doc.text('SCHOOL STAMP: \u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026\u2026', W - M, fy, { align: 'right' })

  doc.setFontSize(7)
  doc.setTextColor(150, 150, 150)
  doc.text('Generated by ShulePulse Teacher', CX, 206, { align: 'center' })

  const safe = (profile?.full_name || 'Teacher').replace(/[^a-zA-Z0-9]+/g, '_')
  const filename = `Timetable_${safe}.pdf`
  return { blob: doc.output('blob'), filename }
}