import { jsPDF } from 'jspdf'
import { applyPlugin } from 'jspdf-autotable'
applyPlugin(jsPDF)
import { loadLogoBase64, logoSizes, fmtRef } from './pdfLogoHelper'
import { weightedScoreMean, marksCell } from '../../../../services/grading'

const PAGE_W = 210
const PAGE_H = 297
const MARGIN = 18
const CONTENT_W = PAGE_W - MARGIN * 2
const FONT = 'helvetica'
const CENTER = PAGE_W / 2

const BLACK = [0, 0, 0]
const DARK = [51, 51, 51]
const MEDIUM = [102, 102, 102]
const LIGHT = [180, 180, 180]
const FAINT = [230, 230, 230]
const BG = [245, 245, 245]
const WHITE = [255, 255, 255]

function fmt(n) {
  return `KES ${Number(n || 0).toLocaleString('en-KE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

function fmtDate(d) {
  if (!d) return '—'
  const dt = new Date(d)
  return dt.toLocaleDateString('en-KE', { day: '2-digit', month: 'short', year: 'numeric' })
}

function fmtDateTimeFull(d) {
  if (!d) return '—'
  const dt = new Date(d)
  return dt.toLocaleDateString('en-KE', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })
}

async function drawSchoolHeader(doc, school, student, title) {
  let y = MARGIN
  const schoolName = school?.name || 'ShulePulse School'
  const schoolAddr = school?.address || ''
  const schoolPhone = school?.phone || ''
  const schoolEmail = school?.email || ''
  const schoolMotto = school?.motto || ''
  const website = school?.website || ''

  const logo = await loadLogoBase64(school)
  if (logo) {
    const ls = logoSizes(logo)
    doc.addImage(logo.dataUrl, 'PNG', CENTER - ls.width / 2, y - 3, ls.width, ls.height)
  } else {
    doc.setDrawColor(...DARK)
    doc.setFillColor(...BG)
    doc.circle(CENTER, y + 7, 10, 'F')
    doc.setDrawColor(...DARK)
    doc.circle(CENTER, y + 7, 10, 'S')
    doc.setFont(FONT, 'bold')
    doc.setFontSize(10)
    doc.setTextColor(...DARK)
    doc.text(schoolName.charAt(0).toUpperCase(), CENTER, y + 10, { align: 'center' })
  }

  y += 24

  doc.setFont(FONT, 'bold')
  doc.setFontSize(16)
  doc.setTextColor(...BLACK)
  doc.text(schoolName.toUpperCase(), CENTER, y, { align: 'center' })

  y += 6
  const contactParts = [schoolAddr, schoolPhone, schoolEmail, website].filter(Boolean)
  if (contactParts.length) {
    doc.setFont(FONT, 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...MEDIUM)
    doc.text(contactParts.join('  |  '), CENTER, y, { align: 'center', maxWidth: CONTENT_W })
    y += 5
  }

  if (schoolMotto) {
    doc.setFont(FONT, 'italic')
    doc.setFontSize(8)
    doc.setTextColor(...LIGHT)
    doc.text(`"${schoolMotto}"`, CENTER, y, { align: 'center' })
    y += 5
  }

  y += 4
  doc.setFont(FONT, 'bold')
  doc.setFontSize(14)
  doc.setTextColor(...DARK)
  doc.text(title, CENTER, y, { align: 'center' })

  y += 6
  doc.setFont(FONT, 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...MEDIUM)
  doc.text(`Student: ${student?.full_name || '—'}  |  Adm: ${student?.admission_number || '—'}  |  Class: ${student?.class || '—'}${student?.stream ? ` ${student.stream}` : ''}`, CENTER, y, { align: 'center' })

  y += 6
  doc.setDrawColor(...DARK)
  doc.setLineWidth(0.5)
  doc.line(MARGIN, y, PAGE_W - MARGIN, y)
  doc.setLineWidth(0.2)
  y += 8

  return y
}

function drawSectionHeader(doc, y, label) {
  doc.setFillColor(...BG)
  doc.rect(MARGIN, y - 4, CONTENT_W, 10, 'F')
  doc.setFont(FONT, 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...BLACK)
  doc.text(label, MARGIN + 4, y + 2)
  return y + 10
}

function drawFooter(doc, y) {
  const remaining = PAGE_H - y - 40
  if (remaining > 0) y += remaining

  doc.setDrawColor(...DARK)
  doc.setLineWidth(0.5)
  doc.line(MARGIN, y, PAGE_W - MARGIN, y)
  doc.setLineWidth(0.2)
  y += 6

  doc.setFont(FONT, 'bold')
  doc.setFontSize(8)
  doc.setTextColor(...DARK)
  doc.text('Generated by ShulePulse ERP', CENTER, y, { align: 'center' })
  y += 4
  doc.setFont(FONT, 'normal')
  doc.setFontSize(7)
  doc.setTextColor(...MEDIUM)
  doc.text(`This is a system-generated report issued on ${fmtDateTimeFull(new Date())}.`, CENTER, y, { align: 'center' })
  y += 3
  doc.text('Valid for official record-keeping purposes.', CENTER, y, { align: 'center' })

  y += 12
  doc.setDrawColor(...LIGHT)
  doc.line(MARGIN, y, MARGIN + 55, y)
  doc.line(PAGE_W - MARGIN - 55, y, PAGE_W - MARGIN, y)
  doc.setFont(FONT, 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...MEDIUM)
  doc.text("Principal's / Administrator's Signature", MARGIN, y + 4)
  doc.text('School Stamp', PAGE_W - MARGIN - 55, y + 4, { align: 'center' })

  y += 14
  doc.setDrawColor(...LIGHT)
  doc.setFillColor(...BG)
  doc.roundedRect(PAGE_W - MARGIN - 20, y - 6, 16, 16, 2, 2, 'FD')
  doc.setFont(FONT, 'normal')
  doc.setFontSize(5)
  doc.setTextColor(...LIGHT)
  doc.text('QR', PAGE_W - MARGIN - 12, y + 2, { align: 'center' })
  doc.text('CODE', PAGE_W - MARGIN - 12, y + 6, { align: 'center' })

  return doc.output('blob')
}

function drawInfoGrid(doc, startY, fields, colCount = 2) {
  const colW = CONTENT_W / colCount
  let y = startY

  fields.forEach((f, i) => {
    const col = MARGIN + (i % colCount) * colW
    const row = Math.floor(i / colCount)
    const yy = y + row * 8
    doc.setFont(FONT, 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...MEDIUM)
    doc.text(f.label, col, yy)
    doc.setFont(FONT, 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...DARK)
    doc.text(f.value, col + 45, yy)
  })

  return y + Math.ceil(fields.length / colCount) * 8 + 6
}

export async function generatePersonalPdf({ school, student }) {
  const doc = new jsPDF('portrait', 'mm', 'a4')
  let y = await drawSchoolHeader(doc, school, student, 'STUDENT PROFILE — PERSONAL INFORMATION')

  y = drawSectionHeader(doc, y, 'PERSONAL DETAILS')

  const fields = [
    { label: 'Full Name', value: student?.full_name || '—' },
    { label: 'Admission No.', value: student?.admission_number || '—' },
    { label: 'Class', value: student?.class || '—' },
    { label: 'Stream', value: student?.stream || '—' },
    { label: 'Gender', value: student?.gender || '—' },
    { label: 'Date of Birth', value: student?.date_of_birth || '—' },
    { label: 'Date Admitted', value: student?.date_admitted || '—' },
    { label: 'Nationality', value: student?.nationality || '—' },
    { label: 'Religion', value: student?.religion || '—' },
    { label: 'Home Address', value: student?.home_address || '—' },
    { label: 'County', value: student?.county || '—' },
    { label: 'Sub-county', value: student?.sub_county || '—' },
    { label: 'Phone', value: student?.phone || '—' },
    { label: 'Email', value: student?.email || '—' },
    { label: 'UPI Number', value: student?.upi_number || '—' },
    { label: 'Birth Cert No.', value: student?.birth_cert_number || '—' },
    { label: 'Previous School', value: student?.previous_school || '—' },
    { label: 'Day/Boarding', value: student?.day_boarding || '—' },
    { label: 'Transport Route', value: student?.transport_route || '—' },
    { label: 'House', value: student?.house || '—' },
    { label: 'Club/Society', value: student?.club || '—' },
    { label: 'Status', value: student?.status || '—' },
  ]

  y = drawInfoGrid(doc, y, fields, 2)

  return drawFooter(doc, y)
}

export async function generateParentsPdf({ school, student }) {
  const doc = new jsPDF('portrait', 'mm', 'a4')
  let y = await drawSchoolHeader(doc, school, student, 'STUDENT PROFILE — PARENT / GUARDIAN INFORMATION')

  const guardians = student?.guardians || []

  if (guardians.length === 0 && !student?.parent_name) {
    doc.setFont(FONT, 'normal')
    doc.setFontSize(10)
    doc.setTextColor(...LIGHT)
    doc.text('No guardian information recorded.', CENTER, y, { align: 'center' })
    return drawFooter(doc, y + 10)
  }

  guardians.forEach((g, i) => {
    if (y > PAGE_H - 60) {
      doc.addPage()
      y = MARGIN
    }

    y = drawSectionHeader(doc, y, g.relationship ? `${g.relationship.toUpperCase()}` : `GUARDIAN ${i + 1}`)

    const fields = [
      { label: 'Name', value: g.name || '—' },
      { label: 'Relationship', value: g.relationship || '—' },
      { label: 'Phone', value: g.phone || '—' },
      { label: 'Email', value: g.email || '—' },
      { label: 'ID Number', value: g.national_id || '—' },
      { label: 'Occupation', value: g.occupation || '—' },
      { label: 'Address', value: g.address || '—' },
      { label: 'Fee Payer', value: g.is_fee_payer ? 'Yes' : 'No' },
      { label: 'Portal Access', value: g.portal_access ? 'Yes' : 'No' },
      { label: 'SMS Notifications', value: g.sms_notification ? 'Yes' : 'No' },
    ]

    y = drawInfoGrid(doc, y, fields, 2)
  })

  if (student?.parent_name) {
    if (y > PAGE_H - 60) {
      doc.addPage()
      y = MARGIN
    }

    y = drawSectionHeader(doc, y, 'PRIMARY CONTACT (LEGACY)')

    const contactFields = [
      { label: 'Name', value: student.parent_name },
      { label: 'Phone', value: student.parent_phone || '—' },
      { label: 'Email', value: student.parent_email || '—' },
    ]

    y = drawInfoGrid(doc, y, contactFields, 2)
  }

  return drawFooter(doc, y)
}

export async function generateMedicalPdf({ school, student }) {
  const doc = new jsPDF('portrait', 'mm', 'a4')
  let y = await drawSchoolHeader(doc, school, student, 'STUDENT PROFILE — MEDICAL INFORMATION')

  y = drawSectionHeader(doc, y, 'MEDICAL DETAILS')

  const fields = [
    { label: 'Blood Group', value: student?.blood_group || '—' },
    { label: 'Allergies', value: student?.allergies || 'None' },
    { label: 'Medical Conditions', value: student?.medical_conditions || 'None' },
    { label: 'Special Needs', value: student?.special_needs || 'None' },
  ]

  y = drawInfoGrid(doc, y, fields, 2)

  return drawFooter(doc, y)
}

export async function generateFeeAccountPdf({ school, student, fee, term, year }) {
  const doc = new jsPDF('portrait', 'mm', 'a4')
  let y = await drawSchoolHeader(doc, school, student, 'STUDENT PROFILE — FEE ACCOUNT')

  y = drawSectionHeader(doc, y, 'FINANCIAL SUMMARY')

  const totalCharged = fee?.totalCharged || 0
  const totalPaid = fee?.totalPaid || 0
  const credit = fee?.credit || 0
  const balance = fee?.balance || 0
  const feeStatus = balance <= 0 ? 'Cleared' : totalPaid > 0 ? 'Partial' : 'Due'

  const cardW = (CONTENT_W - 12) / 4
  const cards = [
    { label: 'Total Charged', value: fmt(totalCharged) },
    { label: 'Applied to Fees', value: fmt(totalPaid) },
    { label: 'Student Credit', value: fmt(credit) },
    { label: 'Balance', value: fmt(Math.abs(balance)) },
  ]

  cards.forEach((card, i) => {
    const cx = MARGIN + i * (cardW + 4)
    doc.setFillColor(...WHITE)
    doc.setDrawColor(...FAINT)
    doc.roundedRect(cx, y, cardW, 18, 2, 2, 'FD')
    doc.setFont(FONT, 'normal')
    doc.setFontSize(7)
    doc.setTextColor(...MEDIUM)
    doc.text(card.label, cx + cardW / 2, y + 6, { align: 'center' })
    doc.setFont(FONT, 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...DARK)
    doc.text(card.value, cx + cardW / 2, y + 14, { align: 'center' })
  })

  y += 24

  doc.setFillColor(...BG)
  doc.setDrawColor(...DARK)
  doc.roundedRect(MARGIN, y, CONTENT_W, 12, 3, 3, 'FD')

  doc.setFont(FONT, 'bold')
  doc.setFontSize(11)
  doc.setTextColor(...BLACK)
  doc.text('OUTSTANDING BALANCE', MARGIN + 10, y + 8)

  doc.setTextColor(...DARK)
  doc.text(fmt(Math.abs(balance)), MARGIN + CONTENT_W / 2, y + 8)

  const badgeBg = feeStatus === 'Cleared' ? [235, 235, 235] : feeStatus === 'Partial' ? [245, 245, 245] : [250, 250, 250]
  doc.setFillColor(...badgeBg)
  doc.setTextColor(...DARK)
  doc.roundedRect(PAGE_W - MARGIN - 40, y + 2, 28, 8, 3, 3, 'F')
  doc.setDrawColor(...FAINT)
  doc.roundedRect(PAGE_W - MARGIN - 40, y + 2, 28, 8, 3, 3, 'S')
  doc.setFont(FONT, 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...DARK)
  doc.text(feeStatus.toUpperCase(), PAGE_W - MARGIN - 26, y + 8, { align: 'center' })

  y += 18

  if (credit > 0) {
    doc.setFont(FONT, 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...MEDIUM)
    doc.text(`STUDENT CREDIT HELD ON ACCOUNT: ${fmt(credit)}`, MARGIN + 10, y)
    y += 7
  }

  const assessments = fee?.assessments || []
  const payments = fee?.payments || []

  if (assessments.length > 0) {
    y = drawSectionHeader(doc, y, `FEE ASSESSMENTS — ${term || '—'} ${year || ''}`)

    const assessRows = assessments.map((a, i) => [
      i + 1,
      a.description || 'Fee Assessment',
      fmt(a.amount_due),
      a.status || '—',
    ])

    doc.autoTable({
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      tableWidth: CONTENT_W,
      head: [['No.', 'Description', 'Amount', 'Status']],
      body: assessRows,
      theme: 'plain',
      styles: { font: FONT, fontSize: 7.5, textColor: [...DARK], cellPadding: { top: 2, right: 2, bottom: 2, left: 2 }, lineColor: [...FAINT], lineWidth: 0.3 },
      headStyles: { font: FONT, fontStyle: 'bold', fontSize: 7.5, textColor: [...MEDIUM], fillColor: [...BG], halign: 'left' },
      columnStyles: {
        0: { cellWidth: 10, halign: 'center' },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 30, halign: 'right' },
        3: { cellWidth: 24, halign: 'center' },
      },
    })
    y = doc.lastAutoTable.finalY + 6
  }

  if (payments.length > 0) {
    if (y > PAGE_H - 60) { doc.addPage(); y = MARGIN }
    y = drawSectionHeader(doc, y, 'PAYMENT HISTORY')

    const payRows = payments.map((p, i) => [
      i + 1,
      fmtDate(p.transaction_date),
      fmtRef(p.reference || p.mpesa_code || '—'),
      p.payment_type || p.payment_method || '—',
      fmt(p.amount),
    ])

    doc.autoTable({
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      tableWidth: CONTENT_W,
      head: [['No.', 'Date', 'Reference', 'Method', 'Amount']],
      body: payRows,
      theme: 'plain',
      styles: { font: FONT, fontSize: 7.5, textColor: [...DARK], cellPadding: { top: 2, right: 2, bottom: 2, left: 2 }, lineColor: [...FAINT], lineWidth: 0.3 },
      headStyles: { font: FONT, fontStyle: 'bold', fontSize: 7.5, textColor: [...MEDIUM], fillColor: [...BG], halign: 'left' },
      columnStyles: {
        0: { cellWidth: 10, halign: 'center' },
        1: { cellWidth: 24 },
        2: { cellWidth: 'auto' },
        3: { cellWidth: 24 },
        4: { cellWidth: 28, halign: 'right' },
      },
    })
    y = doc.lastAutoTable.finalY + 6
  }

  return drawFooter(doc, y)
}

export async function generateAttendancePdf({ school, student, attendance }) {
  const doc = new jsPDF('portrait', 'mm', 'a4')
  let y = await drawSchoolHeader(doc, school, student, 'STUDENT PROFILE — ATTENDANCE RECORD')

  y = drawSectionHeader(doc, y, 'ATTENDANCE SUMMARY')

  const present = attendance?.present || 0
  const absent = attendance?.absent || 0
  const late = attendance?.late || 0
  const total = present + absent + late
  const pct = total > 0 ? Math.round((present / total) * 100) : 0

  const cardW = (CONTENT_W - 12) / 4
  const cards = [
    { label: 'Present', value: String(present) },
    { label: 'Absent', value: String(absent) },
    { label: 'Late', value: String(late) },
    { label: 'Rate', value: `${pct}%` },
  ]

  cards.forEach((card, i) => {
    const cx = MARGIN + i * (cardW + 4)
    doc.setFillColor(...WHITE)
    doc.setDrawColor(...FAINT)
    doc.roundedRect(cx, y, cardW, 18, 2, 2, 'FD')
    doc.setFont(FONT, 'normal')
    doc.setFontSize(7)
    doc.setTextColor(...MEDIUM)
    doc.text(card.label, cx + cardW / 2, y + 6, { align: 'center' })
    doc.setFont(FONT, 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...DARK)
    doc.text(card.value, cx + cardW / 2, y + 14, { align: 'center' })
  })

  y += 24

  const records = attendance?.records || []
  if (records.length > 0) {
    if (y > PAGE_H - 60) { doc.addPage(); y = MARGIN }
    y = drawSectionHeader(doc, y, 'ATTENDANCE RECORDS (LAST 60 DAYS)')

    const attRows = records.map((r, i) => [
      i + 1,
      r.date || '—',
      r.status || '—',
    ])

    doc.autoTable({
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      tableWidth: CONTENT_W,
      head: [['No.', 'Date', 'Status']],
      body: attRows,
      theme: 'plain',
      styles: { font: FONT, fontSize: 7.5, textColor: [...DARK], cellPadding: { top: 2, right: 2, bottom: 2, left: 2 }, lineColor: [...FAINT], lineWidth: 0.3 },
      headStyles: { font: FONT, fontStyle: 'bold', fontSize: 7.5, textColor: [...MEDIUM], fillColor: [...BG], halign: 'left' },
      columnStyles: {
        0: { cellWidth: 10, halign: 'center' },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 24, halign: 'center' },
      },
    })
    y = doc.lastAutoTable.finalY + 6
  }

  return drawFooter(doc, y)
}

export async function generateCbcPdf({ school, student, grades }) {
  const doc = new jsPDF('portrait', 'mm', 'a4')
  let y = await drawSchoolHeader(doc, school, student, 'STUDENT PROFILE — CBC ASSESSMENTS')

  const cbcGrades = grades.filter(g => g.cbe_band || g.performance_level)
  if (cbcGrades.length === 0) {
    doc.setFont(FONT, 'normal')
    doc.setFontSize(10)
    doc.setTextColor(...LIGHT)
    doc.text('No CBC assessments recorded.', CENTER, y, { align: 'center' })
    return drawFooter(doc, y + 10)
  }

  const byTerm = {}
  cbcGrades.forEach(g => {
    const key = `${g.term} ${g.year}`
    if (!byTerm[key]) byTerm[key] = []
    byTerm[key].push(g)
  })

  Object.entries(byTerm).forEach(([termLabel, termGrades]) => {
    if (y > PAGE_H - 60) { doc.addPage(); y = MARGIN }
    y = drawSectionHeader(doc, y, termLabel)

    const rows = termGrades.map((g, i) => [
      i + 1,
      g.subject || '—',
      g.total_score ?? '—',
      g.grade || '—',
      g.cbe_band || '—',
      g.performance_level || '—',
    ])

    doc.autoTable({
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      tableWidth: CONTENT_W,
      head: [['No.', 'Subject', 'Score', 'Grade', 'CBE Band', 'Level']],
      body: rows,
      theme: 'plain',
      styles: { font: FONT, fontSize: 7.5, textColor: [...DARK], cellPadding: { top: 2, right: 2, bottom: 2, left: 2 }, lineColor: [...FAINT], lineWidth: 0.3 },
      headStyles: { font: FONT, fontStyle: 'bold', fontSize: 7.5, textColor: [...MEDIUM], fillColor: [...BG], halign: 'left' },
      columnStyles: {
        0: { cellWidth: 10, halign: 'center' },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 18, halign: 'center' },
        3: { cellWidth: 16, halign: 'center' },
        4: { cellWidth: 22, halign: 'center' },
        5: { cellWidth: 'auto' },
      },
    })
    y = doc.lastAutoTable.finalY + 6
  })

  return drawFooter(doc, y)
}

export async function generateAcademicsPdf({ school, student, grades }) {
  const doc = new jsPDF('portrait', 'mm', 'a4')
  let y = await drawSchoolHeader(doc, school, student, 'STUDENT PROFILE — ACADEMIC RECORDS')

  if (grades.length === 0) {
    doc.setFont(FONT, 'normal')
    doc.setFontSize(10)
    doc.setTextColor(...LIGHT)
    doc.text('No academic records found.', CENTER, y, { align: 'center' })
    return drawFooter(doc, y + 10)
  }

  const byTerm = {}
  grades.forEach(g => {
    const key = `${g.term} ${g.year}`
    if (!byTerm[key]) byTerm[key] = []
    byTerm[key].push(g)
  })

  Object.entries(byTerm).forEach(([termLabel, termGrades]) => {
    if (y > PAGE_H - 60) { doc.addPage(); y = MARGIN }

    const avg = termGrades.length > 0 ? Math.round(weightedScoreMean(termGrades)) : 0

    y = drawSectionHeader(doc, y, `${termLabel}  |  Average: ${avg}%`)

    const rows = termGrades.map((g, i) => [
      i + 1,
      g.subject || '—',
      g.exam_type || 'End Term',
      marksCell(g),
      g.total_score ?? '—',
      g.grade || '—',
    ])

    doc.autoTable({
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      tableWidth: CONTENT_W,
      head: [['No.', 'Subject', 'Exam', 'Marks', 'Total', 'Grade']],
      body: rows,
      theme: 'plain',
      styles: { font: FONT, fontSize: 7.5, textColor: [...DARK], cellPadding: { top: 2, right: 2, bottom: 2, left: 2 }, lineColor: [...FAINT], lineWidth: 0.3 },
      headStyles: { font: FONT, fontStyle: 'bold', fontSize: 7.5, textColor: [...MEDIUM], fillColor: [...BG], halign: 'left' },
      columnStyles: {
        0: { cellWidth: 10, halign: 'center' },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 22, halign: 'center' },
        3: { cellWidth: 24, halign: 'center' },
        4: { cellWidth: 18, halign: 'center' },
        5: { cellWidth: 16, halign: 'center' },
      },
    })
    y = doc.lastAutoTable.finalY + 6
  })

  return drawFooter(doc, y)
}
