// ─── Financial statement PDF renderer (jsPDF) ────────────────────────────────
// One professional renderer shared by the Income Statement, Statement of
// Financial Position, Cash Flow Statement and Statement of Changes in Equity.
// Inputs are the plain data structures produced by financialStatementsUtils,
// so the PDF always mirrors exactly what the General Ledger produced on screen.

import { jsPDF } from 'jspdf'
import { applyPlugin } from 'jspdf-autotable'
import { loadLogoBase64 } from '../admin/fees/utils/pdfLogoHelper'

applyPlugin(jsPDF)

const PAGE_W = 210
const PAGE_H = 297
const MARGIN = 16
const CONTENT_W = PAGE_W - MARGIN * 2
const CENTER = PAGE_W / 2

const PRIMARY = [37, 99, 235]
const CHARCOAL = [15, 23, 42]
const TEXT_DARK = [15, 23, 42]
const TEXT_MUTED = [100, 116, 139]
const BORDER = [226, 232, 240]
const BG = [248, 250, 252]
const WHITE = [255, 255, 255]
const RED = [185, 28, 28]
const GREEN = [5, 150, 105]

const fmtKES = (n) => {
  const v = Number(n) || 0
  const body = `${Math.abs(v).toLocaleString('en-KE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
  return `${v < 0 ? '(' : ''}KES ${body}${v < 0 ? ')' : ''}`
}

const fmtLong = (d) => {
  if (!d) return '—'
  try {
    return new Date(d).toLocaleDateString('en-KE', { day: '2-digit', month: 'long', year: 'numeric' })
  } catch {
    return '—'
  }
}

const isLast = (cols, i) => i === cols.length - 1

export async function generateFinancialStatementPdf({ school, title, periodLabel, sections, summary = [], note }) {
  const doc = new jsPDF('portrait', 'mm', 'a4')
  const schoolName = school?.name || 'ShulePulse'
  const contact = [school?.address, school?.phone, school?.email].filter(Boolean).join('  ·  ')
  const logo = await loadLogoBase64(school).catch(() => null)

  const drawFooter = (pageNumber) => {
    doc.setFillColor(...CHARCOAL)
    doc.rect(0, PAGE_H - 9, PAGE_W, 9, 'F')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(...WHITE)
    doc.text(`Generated by ShulePulse · ${fmtLong(new Date().toISOString())}`, MARGIN, PAGE_H - 3.5)
    doc.text(`Page ${pageNumber}`, PAGE_W - MARGIN, PAGE_H - 3.5, { align: 'right' })
  }

  // ── Accent bar + header ──────────────────────────────────────────────────
  doc.setFillColor(...PRIMARY)
  doc.rect(0, 0, PAGE_W * 0.62, 9, 'F')
  doc.setFillColor(...CHARCOAL)
  doc.rect(PAGE_W * 0.62, 0, PAGE_W - PAGE_W * 0.62, 9, 'F')

  let y = 22
  if (logo && logo.dataUrl) {
    try {
      doc.addImage(logo.dataUrl, 'PNG', MARGIN, 22, 22, 22 * (1 / logo.aspectRatio))
      y = 30
    } catch { /* ignore */ }
  }

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.setTextColor(...TEXT_DARK)
  doc.text(schoolName, MARGIN, y - 4)
  if (contact) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...TEXT_MUTED)
    doc.text(contact, MARGIN, y + 2, { maxWidth: CONTENT_W * 0.6 })
  }

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.setTextColor(...PRIMARY)
  doc.text(title, CENTER, 40, { align: 'center' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...TEXT_DARK)
  doc.text(periodLabel, CENTER, 47, { align: 'center' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  doc.setTextColor(...TEXT_MUTED)
  doc.text(`Currency: Kenya Shillings (KES)`, MARGIN, 54)
  doc.text(fmtLong(new Date().toISOString()), PAGE_W - MARGIN, 54, { align: 'right' })

  doc.setDrawColor(...BORDER)
  doc.setLineWidth(0.4)
  doc.line(MARGIN, 57, PAGE_W - MARGIN, 57)
  doc.setLineWidth(0.2)
  y = 64

  const amtStyle = { halign: 'right', fontStyle: 'bold' }

  // ── Sections ─────────────────────────────────────────────────────────────
  for (const section of sections || []) {
    if (!section) continue
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...PRIMARY)
    doc.text(section.heading, MARGIN, y)
    y += 3

    const head = (section.cols || ['Code', 'Account', 'Amount (KES)']).map((c) => ({
      content: c,
      styles: { fillColor: PRIMARY, textColor: WHITE, fontStyle: 'bold', fontSize: 8, halign: isLast(section.cols, section.cols.indexOf(c)) ? 'right' : 'left' },
    }))

    const body = (section.rows || []).map((r) =>
      r.map((cell, i) => ({
        content: isLast(section.cols, i) && typeof cell === 'number' ? fmtKES(cell) : String(cell),
        styles: { fontSize: 8, fontStyle: i === 0 && typeof r[0] === 'string' && /^[A-Z]/.test(r[0]) ? 'bold' : 'normal', halign: isLast(section.cols, i) ? 'right' : 'left' },
      }))
    )

    const hasTotal = section.total != null && section.totalLabel
    const foot = hasTotal
      ? [[
          { content: section.totalLabel, colSpan: section.cols.length - 1, styles: { fillColor: BG, fontStyle: 'bold', fontSize: 8, textColor: TEXT_DARK } },
          { content: fmtKES(section.total), styles: { fillColor: BG, fontStyle: 'bold', fontSize: 8, textColor: section.total < 0 ? RED : TEXT_DARK, ...amtStyle } },
        ]]
      : []

    doc.autoTable({
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      theme: 'grid',
      head: [head],
      body,
      foot,
      styles: { lineColor: BORDER, lineWidth: 0.2, textColor: TEXT_DARK, cellPadding: 2.2, fontSize: 8, valign: 'middle' },
      columnStyles: { [section.cols.length - 1]: { cellWidth: 38 } },
      didDrawPage: (data) => drawFooter(data.pageNumber),
    })
    y = doc.lastAutoTable.finalY + 8
  }

  // ── Summary rows (grand totals) ──────────────────────────────────────────
  for (const item of summary || []) {
    const emphasized = item.emphasize
    const value = typeof item.value === 'number' ? fmtKES(item.value) : String(item.value)
    doc.autoTable({
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      theme: 'plain',
      head: [],
      body: [[
        { content: item.label, styles: { fillColor: emphasized ? CHARCOAL : BG, textColor: emphasized ? WHITE : TEXT_DARK, fontStyle: 'bold', fontSize: 9.5, cellPadding: 3, halign: 'left' } },
        { content: value, styles: { fillColor: emphasized ? CHARCOAL : BG, textColor: emphasized ? WHITE : (item.value < 0 ? RED : GREEN), fontStyle: 'bold', fontSize: 9.5, cellPadding: 3, halign: 'right' } },
      ]],
      styles: { lineColor: BORDER, lineWidth: 0.2, valign: 'middle' },
      columnStyles: { 0: { cellWidth: CONTENT_W - 38 }, 1: { cellWidth: 38 } },
      didDrawPage: (data) => drawFooter(data.pageNumber),
    })
    y = doc.lastAutoTable.finalY + 4
  }

  // ── Footnote ─────────────────────────────────────────────────────────────
  if (note) {
    y += 4
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(7.5)
    doc.setTextColor(...TEXT_MUTED)
    const lines = doc.splitTextToSize(note, CONTENT_W)
    doc.text(lines, MARGIN, y)
  }

  return doc.output('blob')
}
