-- ============================================================================
-- 072_seed_feature_catalog_and_plans.sql
-- Seeds the feature_catalog with all actual system features and
-- assigns default plan feature sets for Basic / Pro / Enterprise
-- ============================================================================

-- FEATURE CATALOG — All actual system features
INSERT INTO feature_catalog (feature_key, module, label, description, status, sort_order) VALUES
('students.records',           'students',      'Student Records',          'View, add, edit, and manage student profiles',                          'available', 100),
('students.admission',         'students',      'Student Admission',        'Admit new students and manage the admission workflow',                   'available', 110),
('students.attendance',        'students',      'Attendance',               'Take, view, and manage student attendance',                              'available', 120),
('students.promotion',         'students',      'Student Promotion',        'Promote students between classes and grades',                            'available', 130),
('students.transfers',         'students',      'Student Transfers',        'Track student transfers in and out of the school',                       'beta',      140),
('students.discipline',        'students',      'Discipline',               'Record and manage student discipline incidents',                         'beta',      150),
('students.alumni',            'students',      'Alumni',                   'Manage graduated students and alumni records',                           'available', 160),
('students.import',            'students',      'Bulk Import',              'Import students from Excel spreadsheets',                                'available', 170),
('students.documents',         'students',      'Student Documents',        'Upload and manage student documents and certificates',                   'available', 180),

('academics.exams',            'academics',     'Exams',                    'Create exam types, configure weightings, and manage exams',              'available', 200),
('academics.marks_entry',      'academics',     'Marks Entry',              'Enter and manage student marks per subject',                             'available', 210),
('academics.marks_approval',   'academics',     'Marks Approval',           'Review and approve or reject marks submissions',                         'available', 220),
('academics.grades',           'academics',     'Grades',                   'Manage grading system and grade bands (CBE/CBC)',                         'available', 230),
('academics.report_cards',     'academics',     'Report Cards',             'Generate and view student report cards',                                 'available', 240),
('academics.transcripts',      'academics',     'Transcripts',              'Generate academic transcripts for students',                             'available', 250),
('academics.performance',      'academics',     'Performance Analytics',    'Analyze student and subject performance data',                           'available', 260),
('academics.cbc_analysis',     'academics',     'CBC Analysis',             'CBC competency analysis and tracking',                                   'available', 270),
('academics.timetable',        'academics',     'Timetable',                'Create and manage class timetables',                                     'available', 280),
('academics.teacher_review',   'academics',     'Teacher Review',           'Review teacher performance and effectiveness',                           'available', 290),

('finance.fees',               'finance',       'Fee Management',           'Manage fee structures, assessments, and collections',                    'available', 300),
('finance.payments',           'finance',       'Payments',                 'Record and manage student fee payments',                                 'available', 310),
('finance.receipts',           'finance',       'Receipts',                 'Generate and manage payment receipts',                                   'available', 320),
('finance.statements',         'finance',       'Statements',               'Generate student fee statements',                                        'available', 330),
('finance.debtors',            'finance',       'Debtors',                  'View and manage outstanding balances',                                   'available', 340),
('finance.accounting',         'finance',       'Chart of Accounts',        'Manage chart of accounts',                                               'available', 350),
('finance.journal',            'finance',       'Journal Entries',          'Create and manage journal entries',                                      'available', 360),
('finance.ledger',             'finance',       'General Ledger',           'View general ledger transactions',                                       'available', 370),
('finance.expenses',           'finance',       'Expenses',                 'Record and manage school expenses',                                      'available', 380),
('finance.cash_bank',          'finance',       'Cash & Bank',              'Manage cash accounts, bank transfers, and reconciliation',               'available', 390),
('finance.assets',             'finance',       'Fixed Assets',             'Track fixed assets, depreciation, and disposal',                         'available', 400),
('finance.financial_statements','finance',      'Financial Statements',     'Generate income statement, balance sheet, trial balance',                'available', 410),
('finance.ap',                 'finance',       'Accounts Payable',         'Manage suppliers, invoices, payments, and vouchers',                     'available', 420),
('finance.reports',            'finance',       'Finance Reports',          'Generate financial reports and analytics',                               'available', 430),

('payroll.employees',          'payroll',       'Employee Management',      'Manage employee records and payroll data',                               'available', 440),
('payroll.runs',               'payroll',       'Payroll Runs',             'Process payroll runs and generate payslips',                             'available', 450),
('payroll.statutory',          'payroll',       'Statutory Config',         'Configure PAYE, NSSF, SHIF, Housing Levy settings',                      'available', 460),
('payroll.gl_posting',         'payroll',       'GL Posting',               'Post payroll journals to the general ledger',                            'available', 470),
('payroll.reports',            'payroll',       'Payroll Reports',          'Generate payroll reports and analytics',                                 'available', 480),

('hr.staff_directory',         'hr',            'Staff Directory',          'View and manage the staff directory',                                    'available', 500),
('hr.staff_management',        'hr',            'Staff Management',         'Manage staff profiles, roles, and assignments',                           'available', 510),
('hr.departments',             'hr',            'Departments',              'Manage academic and support departments',                                'available', 520),
('hr.comments',                'hr',            'Staff Comments',           'View and manage staff performance comments',                             'available', 530),

('library.catalogue',          'library',       'Library Catalogue',        'Manage library book catalogue',                                          'available', 550),
('library.circulation',        'library',       'Circulation',              'Borrow and return books, manage reservations',                           'available', 560),
('library.fines',              'library',       'Library Fines',            'Track and manage library fines',                                         'available', 570),
('library.reports',            'library',       'Library Reports',          'Generate library usage reports',                                         'available', 580),

('communication.notices',      'communication', 'Notice Board',             'Create and manage school notices',                                       'available', 600),
('communication.messages',     'communication', 'Messages',                 'Internal messaging between staff and parents',                           'available', 610),

('reception.front_office',     'reception',     'Front Office',             'Manage visitors, appointments, and front office requests',               'available', 630),
('reception.calendar',         'reception',     'Calendar',                 'School events calendar and scheduling',                                  'available', 640),

('settings.branding',          'settings',      'Branding',                 'Customize school branding, colors, and logo',                            'available', 660),
('settings.general',           'settings',      'General Settings',         'Configure general school settings',                                      'available', 670),

('platform.reports',           'platform',      'Reports & Analytics',      'School reports and performance analytics',                               'available', 700),
('platform.support',           'platform',      'Support',                  'Submit and manage support tickets',                                      'available', 710)

ON CONFLICT (feature_key) DO NOTHING;

-- ============================================================================
-- DEFAULT PLAN FEATURE ASSIGNMENTS
-- ============================================================================

-- BASIC PLAN — Core student and fee management
INSERT INTO plan_features (plan_key, feature_key) VALUES
('basic', 'students.records'),
('basic', 'students.admission'),
('basic', 'students.attendance'),
('basic', 'students.promotion'),
('basic', 'students.import'),
('basic', 'students.documents'),
('basic', 'academics.exams'),
('basic', 'academics.marks_entry'),
('basic', 'academics.marks_approval'),
('basic', 'academics.grades'),
('basic', 'academics.report_cards'),
('basic', 'academics.timetable'),
('basic', 'finance.fees'),
('basic', 'finance.payments'),
('basic', 'finance.receipts'),
('basic', 'finance.statements'),
('basic', 'finance.debtors'),
('basic', 'hr.staff_directory'),
('basic', 'communication.notices'),
('basic', 'settings.branding'),
('basic', 'settings.general'),
('basic', 'platform.support')
ON CONFLICT DO NOTHING;

-- PRO PLAN — Includes everything in Basic + advanced academics, HR, library, communication
INSERT INTO plan_features (plan_key, feature_key) VALUES
('pro', 'students.records'),
('pro', 'students.admission'),
('pro', 'students.attendance'),
('pro', 'students.promotion'),
('pro', 'students.import'),
('pro', 'students.documents'),
('pro', 'students.transfers'),
('pro', 'students.discipline'),
('pro', 'students.alumni'),
('pro', 'academics.exams'),
('pro', 'academics.marks_entry'),
('pro', 'academics.marks_approval'),
('pro', 'academics.grades'),
('pro', 'academics.report_cards'),
('pro', 'academics.transcripts'),
('pro', 'academics.performance'),
('pro', 'academics.cbc_analysis'),
('pro', 'academics.timetable'),
('pro', 'academics.teacher_review'),
('pro', 'finance.fees'),
('pro', 'finance.payments'),
('pro', 'finance.receipts'),
('pro', 'finance.statements'),
('pro', 'finance.debtors'),
('pro', 'hr.staff_directory'),
('pro', 'hr.staff_management'),
('pro', 'hr.departments'),
('pro', 'hr.comments'),
('pro', 'library.catalogue'),
('pro', 'library.circulation'),
('pro', 'library.fines'),
('pro', 'library.reports'),
('pro', 'communication.notices'),
('pro', 'communication.messages'),
('pro', 'reception.front_office'),
('pro', 'reception.calendar'),
('pro', 'settings.branding'),
('pro', 'settings.general'),
('pro', 'platform.reports'),
('pro', 'platform.support')
ON CONFLICT DO NOTHING;

-- ENTERPRISE PLAN — Includes everything in Pro + full accounting, payroll, assets
INSERT INTO plan_features (plan_key, feature_key) VALUES
('enterprise', 'students.records'),
('enterprise', 'students.admission'),
('enterprise', 'students.attendance'),
('enterprise', 'students.promotion'),
('enterprise', 'students.import'),
('enterprise', 'students.documents'),
('enterprise', 'students.transfers'),
('enterprise', 'students.discipline'),
('enterprise', 'students.alumni'),
('enterprise', 'academics.exams'),
('enterprise', 'academics.marks_entry'),
('enterprise', 'academics.marks_approval'),
('enterprise', 'academics.grades'),
('enterprise', 'academics.report_cards'),
('enterprise', 'academics.transcripts'),
('enterprise', 'academics.performance'),
('enterprise', 'academics.cbc_analysis'),
('enterprise', 'academics.timetable'),
('enterprise', 'academics.teacher_review'),
('enterprise', 'finance.fees'),
('enterprise', 'finance.payments'),
('enterprise', 'finance.receipts'),
('enterprise', 'finance.statements'),
('enterprise', 'finance.debtors'),
('enterprise', 'finance.accounting'),
('enterprise', 'finance.journal'),
('enterprise', 'finance.ledger'),
('enterprise', 'finance.expenses'),
('enterprise', 'finance.cash_bank'),
('enterprise', 'finance.assets'),
('enterprise', 'finance.financial_statements'),
('enterprise', 'finance.ap'),
('enterprise', 'finance.reports'),
('enterprise', 'payroll.employees'),
('enterprise', 'payroll.runs'),
('enterprise', 'payroll.statutory'),
('enterprise', 'payroll.gl_posting'),
('enterprise', 'payroll.reports'),
('enterprise', 'hr.staff_directory'),
('enterprise', 'hr.staff_management'),
('enterprise', 'hr.departments'),
('enterprise', 'hr.comments'),
('enterprise', 'library.catalogue'),
('enterprise', 'library.circulation'),
('enterprise', 'library.fines'),
('enterprise', 'library.reports'),
('enterprise', 'communication.notices'),
('enterprise', 'communication.messages'),
('enterprise', 'reception.front_office'),
('enterprise', 'reception.calendar'),
('enterprise', 'settings.branding'),
('enterprise', 'settings.general'),
('enterprise', 'platform.reports'),
('enterprise', 'platform.support')
ON CONFLICT DO NOTHING;
